### ISSUE TITLE
Pufferfish updater doesn't work (unconfirmed)

### ISSUE THREAD

**Issue by Osiris-Team** [HSGamer/MCServerUpdater#7]
<img src = "https://media.discordapp.net/attachments/709177960720236567/1194916582888067112/image.png?ex=65b217c9&is=659fa2c9&hm=abe18c5ba496e35a997a65fc4952a1b23beb6c53f4f2fc7dfadc2cb8a7a0f946&=&format=webp&quality=lossless&width=1919&height=91"></img>

**Comment by HSGamer** [comment]
Check with the latest snapshot
#5
