### ISSUE TITLE
[DivineMC 1.20.4] Updater don't update DivineMC 

### ISSUE THREAD

**Issue by x9nico** [HSGamer/MCServerUpdater#8]
Hey,

When I'm running MCServerUpdater to Update DivineMC 1.20.4, it makes the chekups about the verison (like normal), and when I make the /version command, it says that it's still not updated.

My start.sh :
`java -jar MCServerUpdater.jar --project divinemc --output spigot.jar`
`java -Xmx3G -Xms1G --add-modules=jdk.incubator.vector -jar spigot.jar --nogui`

Is it normal ?

![image](https://github.com/HSGamer/MCServerUpdater/assets/8091015/66b8ef0a-736f-459f-acc8-15eb120635cd)
![image](https://github.com/HSGamer/MCServerUpdater/assets/8091015/18f602ed-9ea3-4004-ab2e-f5c2b3498cea)

**Comment by x9nico** [comment]
I didn't see any commits about this, is it resolved @HSGamer ?

**Comment by HSGamer** [comment]
> I don't see any commits about this, are you sure is it resolved @HSGamer ?

They already fixed it -_-

**Comment by x9nico** [comment]
> > I don't see any commits about this, are you sure is it resolved @HSGamer ?
> 
> They already fixed it -_-

I just tried to update DivineMC again through MCServerUpdater, it stills lets me somes versions behind...
![Capture d’écran de 2024-04-22 22-23-26](https://github.com/HSGamer/MCServerUpdater/assets/8091015/3c75b571-a81f-4ba4-85c9-6881cf009c79)

**Comment by HSGamer** [comment]
> > > I don't see any commits about this, are you sure is it resolved @HSGamer ?
> > 
> > They already fixed it -_-
> 
> I just tried to update DivineMC again through MCServerUpdater, it stills lets me somes versions behind...
> ![Capture d’écran de 2024-04-22 22-23-26](https://github.com/HSGamer/MCServerUpdater/assets/8091015/3c75b571-a81f-4ba4-85c9-6881cf009c79)
> 

You should ask them instead.

**Comment by x9nico** [comment]
I created the issue => https://github.com/DivineMC/DivineMC/issues/13
